spring:
  profiles:
    active:
    - dev
---
spring:  
  profiles: dev
  application:
    name: microcloud-test-dev   
---
spring:  
  profiles: dafault
  application:
    name: microcloud-test-default   
