spring:
  profiles:
    active:
    - dev
---
server: 
  port: 8001
mybatis: 
  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路径
  type-aliases-package: cn.mldn.vo            # 定义所有操作类的别名所在包
  mapper-locations:                                     # 所有的mapper映射文件
  - classpath:mybatis/mapper/**/*.xml
  
spring:   # 表示该配置直接由Spring容器进行负责处理
  messages:    # 进行资源配置
    basename: i18n/Message,i18n/Pages     # 资源文件的名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: org.gjt.mm.mysql.Driver      # 配置MySQL驱动程序
    url: jdbc:mysql://localhost:3306/mldn8001?useUnicode=true&amp;characterEncoding=utf-8   # 连接地址
    username: root     # 配置数据库用户名
    password: mysqladmin    # 数据库连接密码
    dbcp2:
      min-idle: 5       # 数据库连接池的最小维持连接数
      initial-size: 5   # 初始化提供的连接数
      max-total: 5      # 最大连接数
      max-wait-millis: 200   # 等待连接获取的最大超时时间
  security:  
   session: stateless
   basic: 
    enabled: true     # 启用SpringSecurity的安全配置项
   user: 
    name: mldnjava  # 认证用户名
    password: hello  # 密码
    role: 
    - USER
  profiles: beta
  application:
    name: microcloud-config-dept-client    # 为该服务设置名称
eureka:
  client:  # 客户端进行Eureka注册的配置
    service-url:    # Eureka开启了安全模式后，注册服务的时候也要加上用户名和密码
      defaultZone: http://edmindev:mldnjava@eureka-7001.com:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2  # 设置心跳的时间间隔，默认是30秒
    lease-expiration-duration-in-seconds: 5   # 现在如果超过了5秒的间隔，默认是90秒
    instance-id: dept-8001.com  # 在信息列表时显示主机名称
    prefer-ip-address: true     # 访问的路径显示为IP地址 
info:
  app.name: mldn-microcloud
  company.name: www.mldn.cn
  build.artifactId: $project.artifactId$   # 从pom中读取
  build.version: $project.version$
---
server: 
  port: 8001
mybatis: 
  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路径
  type-aliases-package: cn.mldn.vo            # 定义所有操作类的别名所在包
  mapper-locations:                                     # 所有的mapper映射文件
  - classpath:mybatis/mapper/**/*.xml
  
spring:   # 表示该配置直接由Spring容器进行负责处理
  messages:    # 进行资源配置
    basename: i18n/Message,i18n/Pages     # 资源文件的名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: org.gjt.mm.mysql.Driver      # 配置MySQL驱动程序
    url: jdbc:mysql://localhost:3306/mldn8001?useUnicode=true&amp;characterEncoding=utf-8   # 连接地址
    username: root     # 配置数据库用户名
    password: mysqladmin    # 数据库连接密码
    dbcp2:
      min-idle: 5       # 数据库连接池的最小维持连接数
      initial-size: 5   # 初始化提供的连接数
      max-total: 5      # 最大连接数
      max-wait-millis: 200   # 等待连接获取的最大超时时间
  security:  
   session: stateless
   basic: 
    enabled: true     # 启用SpringSecurity的安全配置项
   user: 
    name: mldnjava  # 认证用户名
    password: hello  # 密码
    role: 
    - USER
  profiles: dev
  application:
    name: microcloud-config-dept-client    # 为该服务设置名称
eureka:
  client:  # 客户端进行Eureka注册的配置
    service-url:    # Eureka开启了安全模式后，注册服务的时候也要加上用户名和密码
      defaultZone: http://edminbeta:mldnjava@eureka-7001.com:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2  # 设置心跳的时间间隔，默认是30秒
    lease-expiration-duration-in-seconds: 5   # 现在如果超过了5秒的间隔，默认是90秒
    instance-id: dept-8001.com  # 在信息列表时显示主机名称
    prefer-ip-address: true     # 访问的路径显示为IP地址 
info:
  app.name: mldn-microcloud
  company.name: www.mldn.cn
  build.artifactId: $project.artifactId$   # 从pom中读取
  build.version: $project.version$
      
